### ISSUE TITLE
The Search Results Layout does not display data if the Pricing Method Field is selected to display in the layout

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#1203]
**[Mingle Card: 1390](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/1390)**
TJ: I'm not sure how I feel about this one ...

Steps to reproduce
------------------

**OS: Windows**

**Browser: Chrome**

**Username/Password: ajfield@qa.com/computer#4**

1.  Open Price Book Item Object and Edit the 'Search Results' to add Pricing Method as one of the fields
2.  Open Mobile App, delete the cache and then Sync
3.  Open Ticket and click on Add an Item

Expected result
---------------

Should display values in all the columns 

Actual Result
-------------

Doesn't display and throws the error below in the Heroku logs

2013-12-18 20:06:47.242913+00:00 app web.1 \- - SERVERWARN -orgId: 00DG0000000ijIEMAY -userId: 005G0000003edxIIAQ -errorDetails: Error:

2013-12-18 20:06:47.242913+00:00 app web.1 \- - Catalog\_Description\_\_c,Name,Breadcrumb\_\_c,toLabel(Pricing\_Method\_\_c),Required\_Item\_\_c

2013-12-18 20:06:47.242913+00:00 app web.1 \- - ^

2013-12-18 20:06:47.242913+00:00 app web.1 \- - ERROR at Row:1:Column:824 EXCEPT

2013-12-18 20:06:47.242913+00:00 app web.1 \- - duplicate field selected: Pricing\_Method\_\_c

2013-12-18 20:06:47.242913+00:00 app web.1 \- - at Request.\_callback (/app/node\_modules/nforce/index.js:1145:15)

2013-12-18 20:06:47.242913+00:00 app web.1 \- - at Request.self.callback (/app/node\_modules/request/request.js:129:22)

2013-12-18 20:06:47.242913+00:00 app web.1 \- - at Request.EventEmitter.emit (events.js:98:17)

2013-12-18 20:06:47.242913+00:00 app web.1 \- - at Request.<anonymous> (/app/node\_modules/request/request.js:873:14)

2013-12-18 20:06:47.242913+00:00 app web.1 \- - at Request.EventEmitter.emit (events.js:117:20)

2013-12-18 20:06:47.243123+00:00 app web.1 \- - at IncomingMessage.<anonymous> (/app/node\_modules/request/request.js:824:12)

2013-12-18 20:06:47.243123+00:00 app web.1 \- - at IncomingMessage.EventEmitter.emit (events.js:117:20)

2013-12-18 20:06:47.243123+00:00 app web.1 \- - at \_stream\_readable.js:920:16

2013-12-18 20:06:47.243123+00:00 app web.1 \- - at process.\_tickCallback (node.js:415:13)

Related Cards
-------------

**Comment by githubbob42** [comment]
### Related Story: #1030 Allow the user to change the display of the "Add Ticket Items" screen ([Mingle](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/1207))
