### ISSUE TITLE
Duplicate Ticket was added while testing on IPad

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#1274]
**[Mingle Card: 1462](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/1462)**
Steps to reproduce
------------------

**OS: iOS**

**Browser: Safari**

**Username/Password: [npfield\_mo@qa.com/Firacat1](mailto:npfield_mo@qa.com/Firacat1)**

1.  Create new Job
2.  Add Ticket with Checklist
3.  Try to change Ticket's Status
4.  Hit Browser Refresh

Expected result
---------------

_Each ticket should have unique ID._

Actual Result
-------------

_2 duplicate tickets_

Model: processing TicketAddedToJob id: 1389217485082

 - Model: Failed to send the following sync message to sforce: id=52cdc7d5f2522902000000c6. error: Salesforce Error

 - DUPLICATE\_VALUE:duplicate value found: FX5\_\_Tracking\_Number\_\_c duplicates value on record with id: a0GG000000YdxZr

 - Error

 - at Object.<anonymous> (/app/sync/event-processor.js:88:29)

 - at Object.<anonymous> (/app/sync/index.js:7:22)

 - From previous event:

 - at Array.reduce (native)

 - at Object.exports.post (/app/sync/index.js:86:16)

 - at /app/sync/worker.js:72:14

 - at /app/sync/worker.js:111:11

 - at /app/node\_modules/mongodb/lib/mongodb/cursor.js:735:13

 - at null.<anonymous> (/app/node\_modules/mongodb/lib/mongodb/db.js:1702:5)

 - at g (events.js:175:14)

 - at EventEmitter.emit (events.js:106:17)

 - at Server.Base.\_callHandler (/app/node\_modules/mongodb/lib/mongodb/connection/base.js:130:25). Elapsed Time: 588 ms

Related Cards
-------------

#1529

**Comment by githubbob42** [comment]
### Related Story: #78 Tracking Number Generator ([Mingle](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/189))
