### ISSUE TITLE
Date parsing error

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#1368]
**[Mingle Card: 1557](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/1557)**
Dev Notes:
----------

I can't reproduce the issue. I created and altered an eform on mobile. The eform has a date field that i set. Both created and updated eform events properly got upserted. 

Steps to reproduce
------------------

```
| | |
|-|-|
|**Version #**|
|1667|
|**OS**|
| |
|**Browser**|
| |
|**Username**|
| |
|**Password**|
| |

  

 


```

Found in the FXDemo logs

2014-01-21 20:50:49.066615+00:00 app web.1 \- - Model: processing EFormCreated id: 1390336143861

2014-01-21 20:50:49.159212+00:00 heroku router \- - at=info method=POST path=/syncDuration host=fxdemo.herokuapp.com request\_id=89e1e2bd-8798-4909-bc21-d2374b1b89b9 fwd="69.15.157.130" dyno=web.1 connect=5ms service=55ms status=200 bytes=37

2014-01-21 20:50:49.632920+00:00 app web.1 \- - Model: processing EFormCreated id: 1390336173624

2014-01-21 20:50:50.107819+00:00 app web.1 \- - Model: processing EFormAltered id: 1390336181852

2014-01-21 20:50:50.438220+00:00 app web.1 \- - Model: processing EFormAltered id: 1390336192347

2014-01-21 20:50:50.793388+00:00 app web.1 \- - Model: processing EFormAltered id: 1390336197174

2014-01-21 20:50:51.096934+00:00 app web.1 \- - Model: Failed to send the following sync message to sforce: id=52dedda85e3993020000000a. error: Salesforce Error

2014-01-21 20:50:51.096934+00:00 app web.1 \- - JSON\_PARSER\_ERROR:Cannot deserialize instance of date from VALUE\_STRING value 1/21/14 at \[line:1, column:2\]

2014-01-21 20:50:51.096934+00:00 app web.1 \- - Error

2014-01-21 20:50:51.096934+00:00 app web.1 \- - at Object.<anonymous> (/app/sync/event-processor.js:88:29)

2014-01-21 20:50:51.096934+00:00 app web.1 \- - at Object.<anonymous> (/app/sync/index.js:7:22)

2014-01-21 20:50:51.096934+00:00 app web.1 \- - From previous event:

2014-01-21 20:50:51.096934+00:00 app web.1 \- - at Array.reduce (native)

Expected result
---------------

_What should happen?_

Actual Result
-------------

_What actually happens?_

Related Cards
-------------

**Comment by githubbob42** [comment]
### Related Story: #512 Server Side Sync ([Mingle](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/654))
