### ISSUE TITLE
Sync page says "Session expired or invalid" but doesn't redirect to login

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#1378]
**[Mingle Card: 1569](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/1569)**
This can be replicated by revoking the session from the console side.

Steps to reproduce
------------------

```
| | |
|-|-|
|**Version #**|
|master|
|**OS**|
| |
|**Browser**|
| |
|**Username**|
| |
|**Password**|
| |

  

 


```

1.  Not sure...
2.  I syned
3.  went to lunch
4.  clicked "sync"
5.  boom

Expected result
---------------

_I assume that it should redirect to SF login page..._

Actual Result
-------------

_"Session expired or invalid" message after trying to sync._

I had to log out and log back in again in order to get past this...

Here is the Response from the dev tools Network tab:

{  
  "stack": "Error: Session expired or invalid  
    at Request.apiRequest \[as \_callback\] (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\nforce\\index.js:1145:15)  
    at Request.init.self.callback (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\request\\index.js:148:22)  
    at Request.EventEmitter.emit (events.js:99:17)  
    at Request.onResponse (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\request\\index.js:891:14)  
    at Request.EventEmitter.emit (events.js:126:20)  
    at IncomingMessage.Request.onResponse.buffer (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\request\\index.js:842:12)  
    at IncomingMessage.EventEmitter.emit (events.js:126:20)  
    at IncomingMessage.\_emitEnd (http.js:366:10)  
    at HTTPParser.parserOnMessageComplete \[as onMessageComplete\] (http.js:149:23)  
    at CleartextStream.socketOnData (http.js:1367:20)  
    at CleartextStream.CryptoStream.\_push (tls.js:526:27)  
    at SecurePair.cycle (tls.js:880:20)  
    at EncryptedStream.CryptoStream.write (tls.js:267:13)  
    at Socket.ondata (stream.js:38:26)  
    at Socket.EventEmitter.emit (events.js:96:17)  
    at TCP.onread (net.js:397:14)\\nFrom previous event:  
    at exports.startServer.app.post.message.body (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\server.js:176:6)  
    at callbacks (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\lib\\router\\index.js:160:37)  
    at Middleware.authenticate (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\sforce\\auth\\index.js:16:24)  
    at callbacks (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\lib\\router\\index.js:160:37)  
    at param (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\lib\\router\\index.js:134:11)  
    at pass (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\lib\\router\\index.js:141:5)  
    at Router.\_dispatch (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\lib\\router\\index.js:169:5)  
    at Object.router (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\lib\\router\\index.js:32:10)  
    at next (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\proto.js:190:15)  
    at Object.Connection.expressOAuth \[as handle\] (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\nforce\\index.js:939:7)  
    at next (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\proto.js:190:15)  
    at store.get.next (C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\middleware\\session.js:311:9)  
    at C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\middleware\\session.js:335:9  
    at C:\\Projects\\Alpine\\Git\\alpine-mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\middleware\\session\\memory.js:50:9",  
  "statusCode": 401,  
  "messageBody": "Session expired or invalid",  
  "errorCode": "INVALID\_SESSION\_ID",  
  "message": "Session expired or invalid"  
}

**Update:** I don't think that this had anything to do with as I was receiving these the other day without this issue, but I was receiving timeout messages trying to sync prior to going to lunch.  

Related Cards
-------------

Test Plan
---------

**Comment by githubbob42** [comment]
### Related Story: #88 Login Online ([Mingle](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/200))
