### ISSUE TITLE
Upload sync worker taking 20 minutes before upload

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#2197]
**[Mingle Card: 2440](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/2440)**
Steps to reproduce
------------------

```
| | |
|-|-|
|**Version #**|
| |
|**OS**|
| |
|**Browser**|
| |
|**Username**|
| |
|**Password**|
| |

  

 


```

1.  A field user at Hulcher created ticket T-81B-6F2-CA6F at approximately 2:09 PM 6/20/14
2.  He sync'd very soon after that. The sync completed with no problems.
3.  He called the back office to tell them that he was done and they could run billing.
4.  The ticket was not in Console.
5.  After roughly 20 minutes the ticket appeared in Console.

Note that the Console user was not trying to search for the ticket, rather they were sitting on the declarative job page and clicking refresh to find the new ticket.

Expected result
---------------

It is expected that under normal circumstances a packet will upload to SFDC within a minute or two of the client completing the sync

Analysis
--------

At 19:05 the worker process crashed because the connection to MongoDB timed out. The problem actually began a little earlier but this time the worker process crashed with error code 8 and heroku did not restart it. Around 19:36 heroku started the worker process again and everything proceeded normally.

Our problem seems to stem from this statement at the top of worker.js

```
// NB: I don't provide a durable connection to mongodb that retries on

// failures. Instead I'm relying on a PaaS's durable restarts.


```

Given the 26 minute delay between restarts I don't think we can rely on Heroku's restarts.

Packet Details:

```
"created\_at": {

    "$date": "2014-06-20T19:10:03.393Z" (Created at 2:10 PM CDT)

},

"\_id": {

    "$oid": "53a4870b6831be0200000013"

}
```

Below is from LogEntries. Notice the time it started processing the model event is 26 minutes after the packet was created! Also, I don't understand the analytics messages.

» 14:05:55.696 2014-06-20 19:05:55.381713+00:00 app worker.1 - -  
» 14:05:55.696 2014-06-20 19:05:55.383156+00:00 app worker.1 - - db.collection ("messages", function (err, collection) {  
» 14:05:55.696 2014-06-20 19:05:55.383161+00:00 app worker.1 - - ^  
» 14:05:55.696 2014-06-20 19:05:55.393116+00:00 app worker.1 - - TypeError: Cannot call method 'collection' of null at collection.find.processed (/app/sync/worker.js:22:6) at /app/node\_modules/mongodb/lib/mongodb/db.js:2043:7 at /app/node\_modules/mongodb/lib/mongodb/db.js:224:16 at null.<anonymous> (/app/node\_modules/mongodb/lib/mongodb/connection/repl\_set.js:920:7) at g (events.js:175:14) at EventEmitter.emit (events.js:95:17) at /app/node\_modules/mongodb/lib/mongodb/connection/repl\_set.js:840:21 at null.<anonymous> (/app/node\_modules/mongodb/lib/mongodb/connection/server.js:541:7) at EventEmitter.emit (events.js:95:17) at null.<anonymous> (/app/node\_modules/mongodb/lib/mongodb/connection/connection\_pool.js:152:15) Exception  
» 14:05:55.768 2014-06-20 19:05:55.382040+00:00 app worker.1 - - /app/sync/worker.js:22  
» 14:05:57.407 2014-06-20 19:05:57.045915+00:00 heroku worker.1 - - State changed from up to crashed

» 14:05:55.696 2014-06-20 19:05:55.393116+00:00 app worker.1 - - TypeError: Cannot call method 'collection' of null at collection.find.processed (/app/sync/worker.js:22:6) at /app/node\_modules/mongodb/lib/mongodb/db.js:2043:7 at /app/node\_modules/mongodb/lib/mongodb/db.js:224:16 at null.<anonymous> (/app/node\_modules/mongodb/lib/mongodb/connection/repl\_set.js:920:7) at g (events.js:175:14) at EventEmitter.emit (events.js:95:17) at /app/node\_modules/mongodb/lib/mongodb/connection/repl\_set.js:840:21 at null.<anonymous> (/app/node\_modules/mongodb/lib/mongodb/connection/server.js:541:7) at EventEmitter.emit (events.js:95:17) at null.<anonymous> (/app/node\_modules/mongodb/lib/mongodb/connection/connection\_pool.js:152:15) Exception Context  
» 14:05:55.768 2014-06-20 19:05:55.382040+00:00 app worker.1 - - /app/sync/worker.js:22 Context  
» 14:05:57.407 2014-06-20 19:05:57.045915+00:00 heroku worker.1 - - State changed from up to crashed Context  
» 14:06:02.057 2014-06-20 19:05:57.009815+00:00 heroku worker.1 - - Process exited with status 8 Context  
» 14:36:34.266 2014-06-20 19:36:34.127236+00:00 heroku worker.1 - - State changed from crashed to starting Context  
» 14:36:41.946 2014-06-20 19:36:41.338854+00:00 heroku worker.1 - - State changed from starting to up Context  
» 14:36:42.601 2014-06-20 19:36:42.252090+00:00 app worker.1 - - Analytics: Attempting connection to mongodb://ds051399-a0.mongolab.com (complete URL supressed). Context  
» 14:36:42.603 2014-06-20 19:36:42.246976+00:00 app worker.1 - - Model: Attempting connection to mongodb://ds051399-a0.mongolab.com (complete URL supressed). Context  
» 14:36:42.683 2014-06-20 19:36:42.257534+00:00 app worker.1 - - Analytics: Success connecting to mongodb://ds051399-a0.mongolab.com. Context  
» 14:36:42.683 2014-06-20 19:36:42.260330+00:00 app worker.1 - - Logging: Success connecting to mongodb://ds051399-a0.mongolab.com. Context  
» 14:36:42.687 2014-06-20 19:36:42.253495+00:00 app worker.1 - - Model: Success connecting to mongodb://ds051399-a0.mongolab.com. Context  
» 14:36:42.687 2014-06-20 19:36:42.258757+00:00 app worker.1 - - Logging: Attempting connection to mongodb://ds051399-a0.mongolab.com (complete URL supressed). Context  
» 14:36:42.993 2014-06-20 19:36:42.677427+00:00 app worker.1 - - Model: Processing queue item: id=53a485fa6831be0200000012 user: /id/00D40000000MuIpEAK/00540000001pAl8AAE Context  
» 14:36:42.998 2014-06-20 19:36:42.679002+00:00 app worker.1 - - Model: Processing queue item complete: id=53a485fa6831be0200000012 Elapsed Time: 2 ms Context  
» 14:36:43.061 2014-06-20 19:36:40.710219+00:00 heroku worker.1 - - Starting process with command \`node workers.js\` Context  
» 14:36:43.075 2014-06-20 19:36:42.677669+00:00 app worker.1 - - Model: Filtering events Context  
» 14:36:43.075 2014-06-20 19:36:42.677972+00:00 app worker.1 - - Model: processing 0 events Context

```
» 14:36:43.700 2014-06-20 19:36:43.584804+00:00 app worker.1 - - Model: Processing queue item: id=53a4870b6831be0200000013 user: /id/00Di0000000hNJbEAM/005i0000003Jj70AAC Context

» 14:36:53.678 2014-06-20 19:36:53.383943+00:00 app worker.1 - - Analytics: Processing queue item: id=53a4870b6831be0200000013 user: /id/00Di0000000hNJbEAM/005i0000003Jj70AAC Context

» 14:36:54.244 2014-06-20 19:36:53.987676+00:00 app worker.1 - - Analytics: Processing queue item complete: id=53a4870b6831be0200000013 Elapsed Time: 602 ms Context

» 14:37:58.681 2014-06-20 19:37:58.386822+00:00 app worker.1 - - Model: Processing queue item complete: id=53a4870b6831be0200000013 Elapsed Time: 74804 ms Context

» 15:57:22.980 2014-06-20 20:57:22.670411+00:00 app worker.1 - - Analytics: Processing queue item: id=53a4870b6831be0200000013 user: /id/00Di0000000hNJbEAM/005i0000003Jj70AAC Context

» 15:57:23.669 2014-06-20 20:57:23.301118+00:00 app worker.1 - - Analytics: Processing queue item complete: id=53a4870b6831be0200000013 Elapsed Time: 629 ms Context


```

According to here, https://devcenter.heroku.com/articles/dynos#dyno-crash-restart-policy, the cool-off period between restarts appears to increase exponentially (10 min, 20 min, 40 min up to 24 hrs).  Instead of crashing when we can't connect to mongo, lets try to reconnect (up to 10 times) before exiting out.

Related Cards
-------------

Test Plan
---------

I've added 3 environment variables (and their defaults):

*   MONGODB\_MAXRETRIES || 10, 
*   MONGODB\_RETRY\_INTERVAL || 30000, 
*   MONGODB\_INTERVAL\_MULTIPLICATOR || 1.5 

Note that since the retry interval in worker.js is set to 30 seconds and we are running the worker process together with the web process in mimosa (with a 30 second timeout), you may want to change the MONGODB\_RETRY\_INTERVAL from 30000 to say, 5000.  Then you should see multiple messages about failed to connect.

The only way I know of to test this is locally with mimosa.  From the command line:

*   Set MONGODB\_RETRY\_INTERVAL from 30000 to about 5000.
*   login to mongo

```
$ mongo
```

*   and then issue the [shutdown](http://docs.mongodb.org/manual/reference/command/shutdown/) command (**IMPORTANT: the docs say NOT to just kill the running process but to use the shutdown command**):

```
\> use admin

> db.shutdownServer({timeoutSecs: 60});

> exit
```

*   Then try to sync...
*   Start up the mongodb process and the messages will go away.

**NOTE:** Since we are working within a 30 second window, and the startup process for mongo may differ depending on your environment, **it's a good idea to have all of your commands ready** (e.g. in a text file) so you can quickly enter or copy/paste the commands.

**Comment by githubbob42** [comment]
### Related Story: #168 Upload Changes ([Mingle](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/291))
