### ISSUE TITLE
Sync Failure

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#255]
**[Mingle Card: 385](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/385)**
The session was actually dead.  It did not get an empty result.  It got no response which is different than empty result.

Unhandled rejection reason: Error: No Office Results  
    at c:\\Users\\dpitre\\Alpine\_Mobile\\src\\sync\\steps\\tickets.js:28:27  
    at Connection.query (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\nforce\\index.js:739:7)  
    at Request.apiRequest \[as \_callback\] (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\nforce\\index.js:1041:14)  
    at Request.init.self.callback (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\request\\index.js:148:22)  
    at Request.EventEmitter.emit (events.js:99:17)  
    at Request.onResponse (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\request\\index.js:876:14)  
    at Request.EventEmitter.emit (events.js:126:20)  
    at IncomingMessage.Request.onResponse.buffer (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\request\\index.js:827:12)  
    at IncomingMessage.EventEmitter.emit (events.js:126:20)  
    at IncomingMessage.\_emitEnd (http.js:366:10)  
    at HTTPParser.parserOnMessageComplete \[as onMessageComplete\] (http.js:149:23)  
    at CleartextStream.socketOnData (http.js:1367:20)  
    at CleartextStream.CryptoStream.\_push (tls.js:526:27)  
    at SecurePair.cycle (tls.js:880:20)  
    at EncryptedStream.CryptoStream.write (tls.js:267:13)  
    at Socket.ondata (stream.js:38:26)  
    at Socket.EventEmitter.emit (events.js:96:17)  
    at TCP.onread (net.js:396:14)  
From previous event:  
    at query (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\sync\\steps\\tickets.js:18:23)  
    at Object.exports.execute (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\sync\\steps\\tickets.js:242:2)  
    at executeSyncSteps (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\sync\\index.js:32:14)  
    at Array.map (native)  
    at executeSyncSteps (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\sync\\index.js:31:16)  
    at Object.exports.get (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\sync\\index.js:81:9)  
    at exports.startServer.express.static.mime.define.text/cache-manifest (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\server.js:115:8)  
    at callbacks (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\lib\\router\\index.js:160:37)  
    at Middleware.authenticate (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\sforce\\auth\\index.js:15:24)  
    at callbacks (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\lib\\router\\index.js:160:37)  
    at param (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\lib\\router\\index.js:134:11)  
    at pass (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\lib\\router\\index.js:141:5)  
    at Router.\_dispatch (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\lib\\router\\index.js:169:5)  
    at Object.router (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\lib\\router\\index.js:32:10)  
    at next (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\proto.js:190:15)  
    at Object.Connection.expressOAuth \[as handle\] (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\nforce\\index.js:940:7)  
    at next (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\proto.js:190:15)  
    at store.get.next (c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\middleware\\session.js:311:9)  
    at c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\middleware\\session.js:335:9  
    at c:\\Users\\dpitre\\Alpine\_Mobile\\src\\node\_modules\\express\\node\_modules\\connect\\lib\\middleware\\session\\memory.js:50:9

**Comment by githubbob42** [comment]
### Related Story: #210 Red Sync Master Data ([Mingle](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/338))
