### ISSUE TITLE
App crashing on oauth problem

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#3032]
**[Mingle Card: 3331](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/3331)**
```
| | |
|-|-|
|Pull Request:|

   [1428](https://github.com/Liquidframeworks/alpine-mobile/pull/1428)|

  

    |
|[Push to Site fxqa1](http://buildslave3.basecamp.liquidframeworks.com:5000/requestQAbuild?qaSite=fxqa1&repoUrl=https%3A%2F%2Fgithub.com%2Fmramad2%2Falpine-mobile&branch=handle-null-oauth&repoName=alpine-mobile&repoOwner=Liquidframeworks&cards=%5B%7B%22projectName%22%3A%22alpine_mobile%22%2C%22cardNumber%22%3A%223331%22%7D%5D&requestNumber=1428&requestUrl=https%3A%2F%2Fgithub.com%2FLiquidframeworks%2Falpine-mobile%2Fpull%2F1428)|
|[Push to Site fxqa2](http://buildslave3.basecamp.liquidframeworks.com:5000/requestQAbuild?qaSite=fxqa2&repoUrl=https%3A%2F%2Fgithub.com%2Fmramad2%2Falpine-mobile&branch=handle-null-oauth&repoName=alpine-mobile&repoOwner=Liquidframeworks&cards=%5B%7B%22projectName%22%3A%22alpine_mobile%22%2C%22cardNumber%22%3A%223331%22%7D%5D&requestNumber=1428&requestUrl=https%3A%2F%2Fgithub.com%2FLiquidframeworks%2Falpine-mobile%2Fpull%2F1428)|
|[Push to Site fxqa3](http://buildslave3.basecamp.liquidframeworks.com:5000/requestQAbuild?qaSite=fxqa3&repoUrl=https%3A%2F%2Fgithub.com%2Fmramad2%2Falpine-mobile&branch=handle-null-oauth&repoName=alpine-mobile&repoOwner=Liquidframeworks&cards=%5B%7B%22projectName%22%3A%22alpine_mobile%22%2C%22cardNumber%22%3A%223331%22%7D%5D&requestNumber=1428&requestUrl=https%3A%2F%2Fgithub.com%2FLiquidframeworks%2Falpine-mobile%2Fpull%2F1428)|
|[Push to Site fxqa4](http://buildslave3.basecamp.liquidframeworks.com:5000/requestQAbuild?qaSite=fxqa4&repoUrl=https%3A%2F%2Fgithub.com%2Fmramad2%2Falpine-mobile&branch=handle-null-oauth&repoName=alpine-mobile&repoOwner=Liquidframeworks&cards=%5B%7B%22projectName%22%3A%22alpine_mobile%22%2C%22cardNumber%22%3A%223331%22%7D%5D&requestNumber=1428&requestUrl=https%3A%2F%2Fgithub.com%2FLiquidframeworks%2Falpine-mobile%2Fpull%2F1428)|
|[Push to Site fxsignoff1](http://buildslave3.basecamp.liquidframeworks.com:5000/requestQAbuild?qaSite=fxsignoff1&repoUrl=https%3A%2F%2Fgithub.com%2Fmramad2%2Falpine-mobile&branch=handle-null-oauth&repoName=alpine-mobile&repoOwner=Liquidframeworks&cards=%5B%7B%22projectName%22%3A%22alpine_mobile%22%2C%22cardNumber%22%3A%223331%22%7D%5D&requestNumber=1428&requestUrl=https%3A%2F%2Fgithub.com%2FLiquidframeworks%2Falpine-mobile%2Fpull%2F1428)|
|[Push to Site fxsignoff2](http://buildslave3.basecamp.liquidframeworks.com:5000/requestQAbuild?qaSite=fxsignoff2&repoUrl=https%3A%2F%2Fgithub.com%2Fmramad2%2Falpine-mobile&branch=handle-null-oauth&repoName=alpine-mobile&repoOwner=Liquidframeworks&cards=%5B%7B%22projectName%22%3A%22alpine_mobile%22%2C%22cardNumber%22%3A%223331%22%7D%5D&requestNumber=1428&requestUrl=https%3A%2F%2Fgithub.com%2FLiquidframeworks%2Falpine-mobile%2Fpull%2F1428)|

    |

  

 


```

Steps to reproduce
------------------

1.  Login to mobile
2.  Login to console and kill the mobile session
3.  Logout of mobile

```
App Crash: Heroku/rcbranch

2015-04-02 15:44:52.689

131 <45>1 2015-04-02T15:44:52.412228+00:00 heroku worker.1 - - State changed from up to crashed

Go to the log: [https://api.heroku.com/myapps/app21917166@heroku.com/addons/logentries](https://api.heroku.com/myapps/app21917166@heroku.com/addons/logentries)

You are receiving this email because your Logentries alarm "App Crash"

has been triggered.

In context:

2015-04-02 15:44:51.601 146 <190>1 2015-04-02T15:44:51.306165+00:00 app worker.1 - - Logging: Successfully opened 'errors' collection.

2015-04-02 15:44:51.634 130 <190>1 2015-04-02T15:44:51.233498+00:00 app worker.1 - - Analytics: Connecting to mongo...

2015-04-02 15:44:51.729 128 <190>1 2015-04-02T15:44:51.241953+00:00 app worker.1 - - Logging: Connecting to mongo...

2015-04-02 15:44:51.729 139 <190>1 2015-04-02T15:44:51.300503+00:00 app worker.1 - - MONGODB: Analytics: Connection Successful.

2015-04-02 15:44:51.729 150 <190>1 2015-04-02T15:44:51.305012+00:00 app worker.1 - - Analytics: Successfully opened 'messages' collection.

2015-04-02 15:44:51.915 97 <190>1 2015-04-02T15:44:51.719361+00:00 app worker.1 - -

2015-04-02 15:44:51.915 159 <190>1 2015-04-02T15:44:51.719477+00:00 app worker.1 - - /app/node\_modules/mongodb/lib/mongodb/connection/server.js:524

2015-04-02 15:44:51.915 115 <190>1 2015-04-02T15:44:51.719715+00:00 app worker.1 - -         throw err;

2015-04-02 15:44:51.915 112 <190>1 2015-04-02T15:44:51.719759+00:00 app worker.1 - -               ^

2015-04-02 15:44:51.915 141 <190>1 2015-04-02T15:44:51.721987+00:00 app worker.1 - - TypeError: Cannot read property 'id' of null

 at splitToken (/app/node\_modules/alpine-logging/lib/assets/auth/token.js:4:35)

 at Object.orgId (/app/node\_modules/alpine-logging/lib/assets/auth/token.js:15:14)

 at Object.exports.log (/app/node\_modules/alpine-logging/lib/assets/logger.js:2:25)

 at /app/node\_modules/alpine-logging/lib/assets/logging-worker.js:80:16

 at /app/node\_modules/alpine-logging/lib/assets/logging-worker.js:120:11

 at Cursor.nextObject (/app/node\_modules/mongodb/lib/mongodb/cursor.js:649:5)

 at commandHandler (/app/node\_modules/mongodb/lib/mongodb/cursor.js:631:14)

 at null.<anonymous> (/app/node\_modules/mongodb/lib/mongodb/db.js:1702:5)

 at g (events.js:180:16)

 at emit (events.js:106:17)

2015-04-02 15:44:52.689 131 <45>1 2015-04-02T15:44:52.412228+00:00 heroku worker.1 - - State changed from up to crashed


```

\--

Expected result
---------------

    The post and analytics app should error the packet and continue working.

Actual Result
-------------

    The post and analytics apps are crashing.

Test Plan

This test needs to be run against what is in release, then against the branch for confirmation.

Test:

1.  Login to Mobile
2.  got to the devtools --> resources --> cookies and clear the heroku session cookie
3.  Logout of Mobile
4.  Check the logs to see that the app crashed

**Comment by githubbob42** [comment]
**Pull Request #1428**
