### ISSUE TITLE
Post is still not reconnecting to mongo

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#3064]
**[Mingle Card: 3363](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/3363)**
```
| | |
|-|-|

```
| | |
|-|-|
|**Version #**|
| |
|**OS**|
| |
|**Browser**|
| |
|**Username**|
| |
|**Password**|
| |

  

 

```

Merrick called this morning, Total Safety reported that the post process was not running again. It had been down for 7 hours. 

```
2015-04-19 09:44:07.650319+00:00 heroku post.1 - - source=post.1 dyno=heroku.18283718.ad281155-e35e-4304-aee7-59cc7f23448d sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.00 sample#load\_avg\_15m=0.00

2015-04-19 09:44:07.650523+00:00 heroku post.1 - - source=post.1 dyno=heroku.18283718.ad281155-e35e-4304-aee7-59cc7f23448d sample#memory\_total=110.52MB sample#memory\_rss=109.56MB sample#memory\_cache=0.00MB sample#memory\_swap=0.96MB sample#memory\_pgpgin=75236pages sample#memory\_pgpgout=47189pages

2015-04-19 09:44:08.666639+00:00 heroku worker.1 - - source=worker.1 dyno=heroku.18283718.4e2ee4da-ad20-4120-9a33-5f778d634224 sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.01 sample#load\_avg\_15m=0.02

2015-04-19 09:44:08.666639+00:00 heroku worker.1 - - source=worker.1 dyno=heroku.18283718.4e2ee4da-ad20-4120-9a33-5f778d634224 sample#memory\_total=71.16MB sample#memory\_rss=69.56MB sample#memory\_cache=0.00MB sample#memory\_swap=1.60MB sample#memory\_pgpgin=60635pages sample#memory\_pgpgout=42827pages

2015-04-19 09:44:09.213834+00:00 heroku web.4 - - source=web.4 dyno=heroku.18283718.a99b199d-98ba-4105-9d6f-0cc4cdf9e028 sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.10 sample#load\_avg\_15m=0.09

2015-04-19 09:44:09.213983+00:00 heroku web.4 - - source=web.4 dyno=heroku.18283718.a99b199d-98ba-4105-9d6f-0cc4cdf9e028 sample#memory\_total=173.43MB sample#memory\_rss=162.18MB sample#memory\_cache=7.53MB sample#memory\_swap=3.73MB sample#memory\_pgpgin=4148612pages sample#memory\_pgpgout=4105167pages

2015-04-19 09:44:10.317834+00:00 heroku fetch.6 - - source=fetch.6 dyno=heroku.18283718.87df1fed-6a85-49a7-b729-8d7419c0ff38 sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.01 sample#load\_avg\_15m=0.04

2015-04-19 09:44:10.317976+00:00 heroku fetch.6 - - source=fetch.6 dyno=heroku.18283718.87df1fed-6a85-49a7-b729-8d7419c0ff38 sample#memory\_total=124.91MB sample#memory\_rss=121.15MB sample#memory\_cache=0.00MB sample#memory\_swap=3.75MB sample#memory\_pgpgin=279802pages sample#memory\_pgpgout=248787pages

2015-04-19 09:44:11.886709+00:00 heroku fetch.5 - - source=fetch.5 dyno=heroku.18283718.99db4db5-bf32-42e4-af50-52064bb5fe3c sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.03 sample#load\_avg\_15m=0.03

2015-04-19 09:44:11.886849+00:00 heroku fetch.5 - - source=fetch.5 dyno=heroku.18283718.99db4db5-bf32-42e4-af50-52064bb5fe3c sample#memory\_total=172.12MB sample#memory\_rss=172.12MB sample#memory\_cache=0.00MB sample#memory\_swap=0.00MB sample#memory\_pgpgin=385881pages sample#memory\_pgpgout=341817pages

2015-04-19 09:44:12.164575+00:00 app post.1 - - **Post: Connection closed or terminated. \[Information only: errored cursor should restart process within a minute...\]**

2015-04-19 09:44:12.177608+00:00 app post.1 - - Post: Connection closed or terminated. \[Information only: errored cursor should restart process within a minute...\]

2015-04-19 09:44:12.232364+00:00 app fetch.6 - - channel error.

2015-04-19 09:44:12.233427+00:00 app fetch.6 - - \[Error: connection closed\]

2015-04-19 09:44:12.574762+00:00 app fetch.4 - - { stack: 'Error: connection closed\\n at null.<anonymous> (/app/node\_modules/alpine-fetch/node\_modules/mongodb/lib/mongodb/connection/server.js:610:98)\\n at emit (events.js:92:17)\\n at null.<anonymous> (/app/node\_modules/alpine-fetch/node\_modules/mongodb/lib/mongodb/connection/connection\_pool.js:171:15)\\n at emit (events.js:98:17)\\n at Socket.<anonymous> (/app/node\_modules/alpine-fetch/node\_modules/mongodb/lib/mongodb/connection/connection.js:550:12)\\n at Socket.emit (events.js:95:17)\\n at TCP.close (net.js:466:12)',

2015-04-19 09:44:12.574768+00:00 app fetch.4 - - message: 'connection closed' }

2015-04-19 09:44:12.575234+00:00 app fetch.4 - - { stack: 'Error: connection closed\\n at null.<anonymous> (/app/node\_modules/alpine-fetch/node\_modules/mongodb/lib/mongodb/connection/server.js:610:98)\\n at emit (events.js:92:17)\\n at null.<anonymous> (/app/node\_modules/alpine-fetch/node\_modules/mongodb/lib/mongodb/connection/connection\_pool.js:171:15)\\n at emit (events.js:98:17)\\n at Socket.<anonymous> (/app/node\_modules/alpine-fetch/node\_modules/mongodb/lib/mongodb/connection/connection.js:550:12)\\n at Socket.emit (events.js:95:17)\\n at TCP.close (net.js:466:12)',

2015-04-19 09:44:12.575237+00:00 app fetch.4 - - message: 'connection closed' }

2015-04-19 09:44:12.576011+00:00 app fetch.4 - - channel error.

2015-04-19 09:44:12.576114+00:00 app fetch.4 - - \[Error: connection closed\]

2015-04-19 09:44:12.848057+00:00 app web.1 - - An error occured reading from the collection NaN.

2015-04-19 09:44:12.869425+00:00 app web.1 - - { \[MongoError: command failed to return results\] name: 'MongoError' }

2015-04-19 09:44:13.022304+00:00 app web.4 - - An error occured reading from the collection NaN.

2015-04-19 09:44:13.032571+00:00 app web.4 - - { \[MongoError: command failed to return results\] name: 'MongoError' }

2015-04-19 09:44:13.146064+00:00 app web.3 - - An error occured reading from the collection NaN.

2015-04-19 09:44:13.159307+00:00 app web.3 - - { \[MongoError: command failed to return results\] name: 'MongoError' }

2015-04-19 09:44:13.235434+00:00 app fetch.6 - - \[Error: Mubsub: broken cursor.\]

2015-04-19 09:44:13.316398+00:00 heroku web.3 - - source=web.3 dyno=heroku.18283718.71c47ae6-ddbf-4d0e-bbb3-27021bfd477a sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.02 sample#load\_avg\_15m=0.02

2015-04-19 09:44:13.235101+00:00 app fetch.6 - - channel error.

2015-04-19 09:44:13.316629+00:00 heroku web.3 - - source=web.3 dyno=heroku.18283718.71c47ae6-ddbf-4d0e-bbb3-27021bfd477a sample#memory\_total=176.74MB sample#memory\_rss=150.30MB sample#memory\_cache=4.78MB sample#memory\_swap=21.66MB sample#memory\_pgpgin=3861383pages sample#memory\_pgpgout=3821682pages

2015-04-19 09:44:13.577595+00:00 app fetch.4 - - channel error.

2015-04-19 09:44:13.577767+00:00 app fetch.4 - - \[Error: Mubsub: broken cursor.\]

2015-04-19 09:44:13.801395+00:00 app web.2 - - An error occured reading from the collection NaN.

2015-04-19 09:44:13.870126+00:00 app web.1 - - An error occured reading from the collection NaN.

2015-04-19 09:44:13.802737+00:00 app web.2 - - { \[MongoError: command failed to return results\] name: 'MongoError' }

2015-04-19 09:44:13.870461+00:00 app web.1 - - \[Error: Mubsub: broken cursor.\]

2015-04-19 09:44:13.894255+00:00 app fetch.4 - - /app/node\_modules/alpine-fetch/node\_modules/mongodb/lib/mongodb/db.js:423

2015-04-19 09:44:13.890988+00:00 app fetch.4 - -

2015-04-19 09:44:13.902995+00:00 app fetch.4 - - if(connection && connection.serverCapabilities.hasListCollectionsCommand) {

2015-04-19 09:44:13.903121+00:00 app fetch.4 - - ^

2015-04-19 09:44:13.925937+00:00 app fetch.4 - - TypeError: Cannot read property 'hasListCollectionsCommand' of undefined at Db.listCollections (/app/node\_modules/alpine-fetch/node\_modules/mongodb/lib/mongodb/db.js:423:49) at Db.createCollection (/app/node\_modules/alpine-fetch/node\_modules/mongodb/lib/mongodb/db.js:1051:8) at create (/app/node\_modules/mubsub/lib/channel.js:108:28) at Channel.create (/app/node\_modules/mubsub/lib/channel.js:116:26) at null.\_onTimeout (/app/node\_modules/mubsub/lib/channel.js:147:30) at Timer.listOnTimeout \[as ontimeout\] (timers.js:112:15) Exception

2015-04-19 09:44:14.034674+00:00 app web.4 - - \[Error: Mubsub: broken cursor.\]

2015-04-19 09:44:14.034262+00:00 app web.4 - - An error occured reading from the collection NaN.

2015-04-19 09:44:14.159741+00:00 app web.3 - - An error occured reading from the collection NaN.

2015-04-19 09:44:14.159915+00:00 app web.3 - - \[Error: Mubsub: broken cursor.\]

2015-04-19 09:44:14.802896+00:00 app web.2 - - An error occured reading from the collection NaN.

2015-04-19 09:44:14.803063+00:00 app web.2 - - \[Error: Mubsub: broken cursor.\]

2015-04-19 09:44:15.136465+00:00 heroku fetch.4 - - State changed from up to crashed Fatal

2015-04-19 09:44:15.117974+00:00 heroku fetch.4 - - Process exited with status 8 ErrorFatal

2015-04-19 09:44:15.137300+00:00 heroku fetch.4 - - State changed from crashed to starting

2015-04-19 09:44:17.234689+00:00 heroku fetch.1 - - source=fetch.1 dyno=heroku.18283718.acf96969-bd4f-40a1-9b4d-962a820e82ad sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.01 sample#load\_avg\_15m=0.14

2015-04-19 09:44:17.234983+00:00 heroku fetch.1 - - source=fetch.1 dyno=heroku.18283718.acf96969-bd4f-40a1-9b4d-962a820e82ad sample#memory\_total=130.97MB sample#memory\_rss=108.74MB sample#memory\_cache=0.56MB sample#memory\_swap=21.68MB sample#memory\_pgpgin=624026pages sample#memory\_pgpgout=596046pages

2015-04-19 09:44:19.121342+00:00 heroku fetch.4 - - Starting process with command \`node ./node\_modules/alpine-fetch/worker.js\`

2015-04-19 09:44:19.797344+00:00 heroku fetch.4 - - State changed from starting to up

2015-04-19 09:44:20.793903+00:00 app fetch.4 - - Detected 1024 MB available memory, 512 MB limit per process (WEB\_MEMORY)

2015-04-19 09:44:20.793918+00:00 app fetch.4 - - Recommending WEB\_CONCURRENCY=2

2015-04-19 09:44:21.657272+00:00 heroku web.1 - - source=web.1 dyno=heroku.18283718.ad8bc547-bf90-4428-9cae-3140571a4f39 sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.05 sample#load\_avg\_15m=0.08

2015-04-19 09:44:21.657272+00:00 heroku web.1 - - source=web.1 dyno=heroku.18283718.ad8bc547-bf90-4428-9cae-3140571a4f39 sample#memory\_total=194.80MB sample#memory\_rss=169.07MB sample#memory\_cache=5.45MB sample#memory\_swap=20.28MB sample#memory\_pgpgin=2935436pages sample#memory\_pgpgout=2890758pages

2015-04-19 09:44:22.326314+00:00 heroku fetch.3 - - source=fetch.3 dyno=heroku.18283718.5240673b-0599-457e-854a-c6e33c605c57 sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.00 sample#load\_avg\_15m=0.00

2015-04-19 09:44:22.326451+00:00 heroku fetch.3 - - source=fetch.3 dyno=heroku.18283718.5240673b-0599-457e-854a-c6e33c605c57 sample#memory\_total=145.02MB sample#memory\_rss=144.49MB sample#memory\_cache=0.00MB sample#memory\_swap=0.52MB sample#memory\_pgpgin=368036pages sample#memory\_pgpgout=331046pages

2015-04-19 09:44:24.534729+00:00 heroku fetch.2 - - source=fetch.2 dyno=heroku.18283718.775abfcf-02d6-4e50-984e-eedb1d153e4f sample#load\_avg\_1m=0.00 sample#load\_avg\_5m=0.00 sample#load\_avg\_15m=0.00

2015-04-19 09:44:24.534958+00:00 heroku fetch.2 - - source=fetch.2 dyno=heroku.18283718.775abfcf-02d6-4e50-984e-eedb1d153e4f sample#memory\_total=137.38MB sample#memory\_rss=130.80MB sample#memory\_cache=0.66MB sample#memory\_swap=5.91MB sample#memory\_pgpgin=404982pages sample#memory\_pgpgout=371327pages

```

Expected result
---------------

_What should happen?_

Actual Result
-------------

_What actually happens?_

Related Cards
-------------

Card #3284

Test Plan
---------


```

**Comment by githubbob42** [comment]
**Pull Request #1445**
