### ISSUE TITLE
Sync and login issues while testing 3404

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#3112]
**[Mingle Card: 3414](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/3414)**
See #3416
---------

Steps to reproduce
------------------

```
| | |
|-|-|
|**Version #**|
|FXQA2: 100|
|**OS**|
| |
|**Browser**|
| |
|**Username**|
|ajf@t3.com|
|**Password**|
|computer47|

  

 


```

1.  Upversion to 3404
2.  Create a ticket, add ticket items, logs, eForm, files
3.  Sync twice
4.  Change the status of the ticket to 'Ready for Signature'
5.  Add the ticket report and a signed ticket report which moved the ticket to Approved Status
6.  Sync twice

Expected result
---------------

Sync is succesful and the reports are synced successfull

Actual Result
-------------

Reports are not synced and getting the POST Error '500'.

message: "Cannot read property 'oauth' of undefined"  
stack: "TypeError: Cannot read property 'oauth' of undefined↵ at logErrors (/app/server.js:76:37)↵ at Layer.handle\_error (/app/node\_modules/express/lib/router/layer.js:58:5)↵ at trim\_prefix (/app/node\_modules/express/lib/router/index.js:300:13)↵ at /app/node\_modules/express/lib/router/index.js:270:7↵ at Function.proto.process\_params (/app/node\_modules/express/lib/router/index.js:321:12)↵ at next (/app/node\_modules/express/lib/router/index.js:261:10)↵ at Layer.handle\_error (/app/node\_modules/express/lib/router/layer.js:54:12)↵ at trim\_prefix (/app/node\_modules/express/lib/router/index.js:300:13)↵ at /app/node\_modules/express/lib/router/index.js:270:7↵ at Function.proto.process\_params (/app/node\_modules/express/lib/router/index.js:321:12)"  
type: "non\_object\_property\_load"

Logged out and logged back in and the sync does not automatically restarts.

Related Cards
-------------

Test Plan
---------

**Comment by githubbob42** [comment]
### Related Story: #3103 TECH DEBT: cleanup usage of expressjs ([Mingle](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/3404))
