### ISSUE TITLE
server error: Too Many Parameters

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#3116]
**[Mingle Card: 3419](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/3419)**
YM: Turns out our logout process is POSTing invalid data to the /session endpoint that tries to invalidate the current session. The POST body wasn't properly encoded and the content type wasn't specified so the JSON middleware wasn't handling the request. The client code should be fixed to submit valid JSON after which point we don't have anything that would require the bodyParser.urlencoded middleware and can be removed.

CC: Looks like this error is being thrown here: https://github.com/expressjs/body-parser/blob/master/lib/types/urlencoded.js#L137-L138

Without knowing the POST request that triggered this exception, it's going to be hard to track down. However, it might be possible to avoid this problem altogether by removing this LOC: https://github.com/Liquidframeworks/alpine-mobile/blob/master/src/server.js#L41. I don't think we ever current accept post-bodies that are not either JSON, or multi-part form data (attachments).

Here are the list of URLS that we accept POSTs to:

`// accept json app.post('/refresh', connection.refresh)`

`app.post('/session', syncQueue.logout, connection.revokeOAuth);`

`app.post('/sync', analytics.measureUpload, analytics.countUpload, syncQueue.append);`

`app.post('/sync/duration', analytics.measureDownload, syncQueue.duration, syncQueue.append);`

`app.post('/syncerrors/process', queuedErrors.process);`

`app.post('/attachment/index', resolveChatterIds);`

`// accept multi-part`

`app.post('/attachment/:sobjectId', upload);`

`// requires no body parsing (uses url param only)`

`app.post('/syncerrors/:packageId', queuedErrors.markAsProcessed);`

Given that we don't actually POST forms with urlencoded bodies, removing the bodyParser.urlencoded should avoid this issue altogether without side-effects.

`Saw this error in console after a sync:`

```
00DF00000005FZiMAM/005F0000003LCszIAG Post: Processing queue item complete: id=554b78438621698885000004 Elapsed Time: 726 ms

SERVERERROR -orgId: null -userId: null -errorDetails: Error

too many parameters

Error: too many parameters

  at queryparse (/Users/ymorita/Work/alpine-mobile/src/node_modules/body-parser/lib/types/urlencoded.js:138:17)

  at parse (/Users/ymorita/Work/alpine-mobile/src/node_modules/body-parser/lib/types/urlencoded.js:71:9)

  at /Users/ymorita/Work/alpine-mobile/src/node_modules/body-parser/lib/read.js:102:18

  at IncomingMessage.onEnd (/Users/ymorita/Work/alpine-mobile/src/node_modules/body-parser/node_modules/raw-body/index.js:149:7)

  at IncomingMessage.g (events.js:199:16)

  at IncomingMessage.emit (events.js:104:17)

  at _stream_readable.js:908:16

  at process._tickCallback (node.js:355:11)

channel error.

{ [MongoError: cursor killed or timed out] name: 'MongoError' }

Post: Error when iterating over capped collection: Error: Cursor item is null.

Post: Cursor has been closed/terminated. Re-starting Alpine-Post...

Post: Connecting to mongo...
```

I'm suspecting some other breaking changes in the new body-parser module might have something to do with this. I have not been able to determine what causes this exception.

Here's a link with a possible cause: http://blog.matthewdfuller.com/2014/10/nodejs-error-too-many-parameters-at.html

Makes sense we might get this if the upload packet gets large.

Steps to reproduce
------------------

```
| | |
|-|-|
|**Version #**|
| |
|**OS**|
| |
|**Browser**|
| |
|**Username**|
| |
|**Password**|
| |

  

 


```

1.  log out

Expected result
---------------

_console has a audit log entries related to logging out (see #3276)_

Actual Result
-------------

console has no audit log entries and server is throwing an exception

Related Cards

Test Plan
---------

Verify that #3276 works. It is likely broken at this time.

### Checklist for Merging

*   How is this tested in Selenium? 
    *   we may be able to automate this by going to console and verifying audit entries are created...
*   Do we have adequate unit testing? 
*   Where is this covered in documentation?
*   Where is this in Tarantula? 
    *   **Test Case: **Audit Log for LoggedOutWithData

**Comment by githubbob42** [comment]
**Pull Request #1476**
