### ISSUE TITLE
Clicking on 'Assigned To' field throws error

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#3169]
**[Mingle Card: 3474](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/3474)**
Analysis
--------

The 'Assigned To' field is set up to point to a User (rather than a contact). Mobile does not support user lookups.

We should probably do two things here:

1) Prevent the app "locking up" (a spinner/mask that never fades) by either:

*   Showing an empty search dialog (since we have no user data/metadata)
*   Avoiding showing an editable control for reference fields that are not lookups

2) Correct the test case to use Contact for the assigned to field (rather than User).

Steps to reproduce
------------------

```
| | |
|-|-|
|**Version #**|
|dev.fieldfx.com - 4.0.1.2880|
|**OS**|
| |
|**Browser**|
| |
|**Username**|
|ajf@t3.com|
|**Password**|
|computer47|

  

 


```

1.  Click to create a ticket
2.  Click on 'Assigned To' field

Expected result
---------------

Displays list of users

Actual Result
-------------

Spinners comes on and keeps on spinning. Turned on debug=true and then it throws the error in devConsole

TypeError: Cannot read property 'searchColumns' of undefined  
    at e.setColumns (eval at startWithResources (https://dev.fieldfx.com/app/resources.js:1:85), <anonymous>:272:1664)  
    at eval (eval at startWithResources (https://dev.fieldfx.com/app/resources.js:1:85), <anonymous>:272:1239)  
    at eval (eval at startWithResources (https://dev.fieldfx.com/app/resources.js:1:85), <anonymous>:82:389)  
    at l (eval at startWithResources (https://dev.fieldfx.com/app/resources.js:1:85), <anonymous>:14:2988)  
    at p (eval at startWithResources (https://dev.fieldfx.com/app/resources.js:1:85), <anonymous>:14:3258)  
    at b (eval at startWithResources (https://dev.fieldfx.com/app/resources.js:1:85), <anonymous>:14:3793)  
    at MutationObserver.o (eval at startWithResources (https://dev.fieldfx.com/app/resources.js:1:85), <anonymous>:14:1374)

Related Cards
-------------

Test Plan
---------

### Checklist for Merging

*   How is this tested in Selenium? 
*   Do we have adequate unit testing? 
*   Where is this covered in documentation?
*   Where is this in Tarantula?

**Comment by githubbob42** [comment]
### Related Story: #3131 As the Ops Mgr, I need to make sure that my field engineers can only see their tickets ([Mingle](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/3434))

**Comment by githubbob42** [comment]
**Pull Request #1501**
