### ISSUE TITLE
Sync Error AL-1943

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#3592]
**[Mingle Card: 3910](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/3910)**
Analysis
--------

CC- a0p1a000004x1l3eaa isn't a syncId, so salesforce is throwing the “not found” error when it tries to find a record with that value in the FX5\_\_SyncID\_\_c field. a0p1a000004x1l3eaa is a salesforce identifier, not a mobile generated guid, so unless someone manually edited the sync id in console, a record should never exist with a sync id that looks like that.

JM 2-4: I can confirm no one is editing Sync ID in Console. This looks like a problem with the assignment if Sync IDs in mobile from our side. 

Steps to reproduce
------------------

```
| | |
|-|-|
|**Version #**|
|Beta Bi-Weekly on ~3.0.8|
|**OS**|
|Win 7|
|**Browser**|
|WindowsChrome 47.0.2526.111|
|**Username**|
|jmelchor@pioneer.com   |
|**Password**|
|fieldfx2|

  

 


```

1.  Open Job J-C43-9CD-FD08
2.  Open ticket T-BEC-BDA-AE3F
3.  Go to ticket items
4.  Select ticket item **Run 0/Setup Charges** and add child to it with item code 15080

This will cause the error. It is only on this price book and this price book was created through deep copy.

**Alternative Test:**

Credentials: ajf@t3.com/computer47

1.  On console, add ticket item that has dynamic parenting enabled
2.  Make sure Dynamic parenting is enabled on ticket item
3.  Make sure Dynamic parenting is on the layout that’s tied to a profile associated with the mobile to the user.(Get around issue: 3704)
4.  Sync
5.  On Mobile, navigate to Ticket/Items, and select the item that was added
6.  Click on Dynamic parenting icon
7.  Add another item
8.  Sync

Expected Result: sync upsert is successful

Actual Result: Sync fails with error shown below

1.  Review Audit log error: AL-1943.  
    Failed to upsert object : INVALID\_FIELD : Foreign key external ID: a0p1a000004x1l3eaa not found for field FX5\_\_SyncID\_\_c in entity FX5\_\_Ticket\_Item\_\_c
2.  Confirm that External ID Above doesn't exist for Ticket Item ID. 
3.  This sync error appears to be complaining it can’t find the parent item however the parent item is visible in console. [https://fieldfx-2666.cloudforce.com/a0P1a000004x1l3EAA](https://fieldfx-2666.cloudforce.com/a0P1a000004x1l3EAA)
4.  Upon re-running the packet, I get the below error again. 
5.  {"message":"Failed to upsert object : INVALID\_FIELD : Foreign key external ID: a0p1a000004x1l3eaa not found for field FX5\_\_SyncID\_\_c in entity FX5\_\_Ticket\_Item\_\_c","SalesforceError":{"stack":"Error: _Foreign key external ID: a0p1a000004x1l3eaa not found for field FX5\_\_SyncID\_\_c in entity FX5\_\_Ticket\_Item\_\_c_\\n at Request.\_callback (/app/node\_modules/nforce/index.js:1145:15)\\n at Request.self.callback (/app/node\_modules/request/request.js:199:22)\\n at Request.emit (events.js:98:17)\\n at Request.<anonymous> (/app/node\_modules/request/request.js:1160:14)\\n at Request.emit (events.js:117:20)\\n at IncomingMessage.<anonymous> (/app/node\_modules/request/request.js:1111:12)\\n at IncomingMessage.emit (events.js:117:20)\\n at \_stream\_readable.js:944:16\\n at process.\_tickDomainCallback)(node.js:492:13)","message":"Foreign key external ID: a0p1a000004x1l3eaa not found for field FX5\_\_SyncID\_\_c in entity FX5\_\_Ticket\_Item\_\_c","errorCode":"INVALID\_FIELD","statusCode":400,"messageBody":"Foreign key external ID: a0p1a000004x1l3eaa not found for field FX5\_\_SyncID\_\_c in entity FX5\_\_Ticket\_Item\_\_c"},"name":"SalesforceError","statusCode":400,"eventId":1453494380167,"trackingNumber":"T-BEC-BDA-AE3F"}

This has been duplicated in another Ticket with the same exact error. Please see AL-2033 and ticket T-141-5D2-EF2B. 

Ticket: [https://fieldfx-2666.cloudforce.com/a0R1a000001AaM6](https://fieldfx-2666.cloudforce.com/a0R1a000001AaM6)

Item: Parent Ticket Item : a0P1a000004xDs0EAE   
Ticket Item: [https://fieldfx-2666.cloudforce.com/a0P1a000004xDs0EAE](https://fieldfx-2666.cloudforce.com/a0P1a000004xDs0EAE)

### Checklist for Merging

*   Enter the Pull Request number in the card properties
*   How is this tested in Selenium? 
*   Do we have adequate unit testing? 
*   Where is this covered in documentation?
*   Where is this in Tarantula?

**Comment by githubbob42** [comment]
**Pull Request #1721**
