### ISSUE TITLE
Failed uploads give false error message

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#4145]
**[Mingle Card: 4480](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/4480)**
Steps to Reproduce
------------------

```
| | |
|-|-|
|**Version #**|4.0.1.3352|
|**Hardware**| |
|**OS**| |
|**Browser**| |
|**Username**| |
|**Password**|Use LastPass|
|ORG ID| |
|User ID| |
|RayGun Error ID| |
  
 

```

This has been reported by Pioneer with failed quote updates. The error message always come across as 

```
<errorCode>INVALID\_SESSION\_ID</errorCode>
<message>Session expired or invalid</message>

```

We are also seeing this in the selenium ORGs against master. Here is some details from a failed upload from a selenium test:

Links below are from the selenium ORG sandbox #1 (credentials in LastPass)

The audit log entry is [AL-9898](https://cs50.salesforce.com/a0i3B000000BuuF). It is failing on event 1474889046402 which is below. The audit log message is 

PATCH[https://cs50.salesforce.com/services/data/v34.0/sobjects/FX5\_\_Quote\_\_c/FX5\_\_SyncID\_\_c/Q-FBE-302-D0AD](https://cs50.salesforce.com/services/data/v34.0/sobjects/FX5__Quote__c/FX5__SyncID__c/Q-FBE-302-D0AD) failed with statusCode 400

    {

        "eventname": "model:event-queued",

        "payload": {

            "url": "/services/data/v34.0/sobjects/FX5\_\_Quote\_\_c/FX5\_\_SyncID\_\_c/Q-FBE-302-D0AD",

            "method": "PATCH",

            "body": {

                "FX5\_\_Status\_\_c": "a0OF000000MesQcMAJ"

            },

            "sobject": "FX5\_\_Quote\_\_c",

            "syncid": "d90f8386-aed2-48cc-9ec4-ddc70a37922a"

        },

        "eventId": 1474889046402

    },

It is trying to change to this [status](https://cs50.salesforce.com/a0OF000000MesQcMAJ), which seems reasonable, at least at first glance.

Here are the relevant logs from LogEntries

```
app web.1 - - 00D3B0000008klGUAQ/0050G000008XyEkQAK Post: Failed to send the following sync message to sforce: id=57e90660bbaf73030053c830
app web.1 - - 00D3B0000008klGUAQ/0050G000008XyEkQAK Post: Processing queue item complete: id=57e90660bbaf73030053c830 Elapsed Time: 16951 ms
app web.1 - - SERVERERROR -orgName: LiquidFrameworks, Inc. -userName: npfield20@soasta1.com.s1 -errorDetails: Error
app web.1 - - PATCH [https://cs50.salesforce.com/services/data/v34.0/sobjects/FX5\_\_Quote\_\_c/FX5\_\_SyncID\_\_c/Q-FBE-302-D0AD](https://cs50.salesforce.com/services/data/v34.0/sobjects/FX5__Quote__c/FX5__SyncID__c/Q-FBE-302-D0AD) failed with statusCode 400
app web.1 - - Error: PATCH [https://cs50.salesforce.com/services/data/v34.0/sobjects/FX5\_\_Quote\_\_c/FX5\_\_SyncID\_\_c/Q-FBE-302-D0AD](https://cs50.salesforce.com/services/data/v34.0/sobjects/FX5__Quote__c/FX5__SyncID__c/Q-FBE-302-D0AD) failed with statusCode 400 at /app/node\_modules/alpine-post/lib/handlers/event-queued.js:24:11 at /app/node\_modules/q/q.js:1229:26 at \_fulfilled (/app/node\_modules/q/q.js:834:54) at self.promiseDispatch.done (/app/node\_modules/q/q.js:863:30) at Promise.promise.promiseDispatch (/app/node\_modules/q/q.js:796:13) at /app/node\_modules/q/q.js:556:49 at runSingle (/app/node\_modules/q/q.js:137:13) at flush (/app/node\_modules/q/q.js:125:13) at \_combinedTickCallback (internal/process/next\_tick.js:67:7) at process.\_tickDomainCallback (internal/process/next\_tick.js:122:9) Exception


```

Here is the full audit log

```
| | |
|-|-|
 
  
   
   

Audit Log Detail
----------------

   |
      |
  
 

```

```
| | |
|-|-|
 
  
   Audit Log ID|
   
   

AL-9898

   |
   Owner|
   
   

[![npfield20](https://c.cs50.content.force.com/profilephoto/005/T "npfield20")![](https://cs50.salesforce.com/s.gif)](https://cs50.salesforce.com/0050G000008XyEk "npfield20")[npfield20](https://cs50.salesforce.com/0050G000008XyEk) [\[Change\]](https://cs50.salesforce.com/a0i3B000000BuuF/a?retURL=%2Fa0i3B000000BuuF)

   |
  
   Fixed|
   
   

![Not Checked](https://cs50.salesforce.com/img/checkbox_unchecked.gif "Not Checked")

   |
    |
    |
  
   Event Date![](https://cs50.salesforce.com/s.gif)|
   
   

9/26/2016 6:28 AM

   |
    |
    |
  
   Created By|
   
   

[npfield20](https://cs50.salesforce.com/0050G000008XyEk), 9/26/2016 6:28 AM

   |
   Last Modified By|
   
   

[npfield20](https://cs50.salesforce.com/0050G000008XyEk), 9/26/2016 6:28 AM

   |
  
   Message![](https://cs50.salesforce.com/s.gif)|
   
   

PATCH[https://cs50.salesforce.com/services/data/v34.0/sobjects/FX5\_\_Quote\_\_c/FX5\_\_SyncID\_\_c/Q-FBE-302-D0AD](https://cs50.salesforce.com/services/data/v34.0/sobjects/FX5__Quote__c/FX5__SyncID__c/Q-FBE-302-D0AD) failed with statusCode 400

   |
    |
    |
  
   Package Id![](https://cs50.salesforce.com/s.gif)|
   
   

57e90660bbaf73030053c830

   |
    |
    |
  
   Tracking Number![](https://cs50.salesforce.com/s.gif)|
   
   

   |
    |
    |
  
   Type![](https://cs50.salesforce.com/s.gif)|
   
   

SyncUploadError

   |
    |
    |
  
   URL![](https://cs50.salesforce.com/s.gif)|
   
   

[https://hunterpeaksandbox.herokuapp.com/syncerr...](https://hunterpeaksandbox.herokuapp.com/syncerrors/57e90660bbaf73030053c830)

   |
    |
    |
  
   User![](https://cs50.salesforce.com/s.gif)|
   
   

[npfield20](https://cs50.salesforce.com/0050G000008XyEk)

   |
    |
    |
  
   Event Id![](https://cs50.salesforce.com/s.gif)|
   
   

1474889046402

   |
  
 

```

Expected Result
---------------

Should get a meaningful error message

Actual Result
-------------

Error message is always 

```
Session expired or invalid
```

_Analysis_
----------

Related Cards
-------------

Test Plan
---------

**Comment by githubbob42** [comment]
**Pull Request #2017**
