### ISSUE TITLE
Remove + button when a ticket/job/quote has no initial status

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#4404]
**[Mingle Card: 4742](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/4742)**
Analysis
--------

Previous behavior was to remove record types from ticket/job create screens that are not tied to a status with the initial Status flag set to true. Wrote some sample code that worked out pretty well using this approach, and we display an empty create screen with no add button.

!recordtypes-a6d9d6.png!

Narrative
---------

Some customers don’t want field users to create tickets or jobs.

Acceptance Criteria
-------------------

If there is no initial status for a job, ticket or quote, then do not show the + button to create a new job, ticket or quote.

_Analysis_
----------

Why can’t we also detect that the user does not have create permission?

For an experiment, I removed access to create a ticket. When I tried to create the ticket in Mobile I got this error:

```
Uncaught (in promise) einner: DOMException: Failed to execute 'put' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.
    at eval (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:29737)
    at eval (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:24407)
    at eval (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:31934)
    at L (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:7845)
    at new B (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:6142)
    at eval (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:31417)
    at Function.B.newPSD (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:248:18484)
    at G.\_promise (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:31276)
    at U.i \[as \_tpf\] (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:13269)
    at U.\_idbstore (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:24372)message: "Failed to execute 'put' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value."name: "DataError"stack: "Error: Failed to execute 'put' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.↵    at eval (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:29737)↵    at eval (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:24407)↵    at eval (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:31934)↵    at L (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:7845)↵    at new B (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:6142)↵    at eval (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:31417)↵    at Function.B.newPSD (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:248:18484)↵    at G.\_promise (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:31276)↵    at U.i \[as \_tpf\] (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:13269)↵    at U.\_idbstore (eval at startWithResources (https://hunterpeak.herokuapp.com/app/resources.js:1:71), <anonymous>:247:24372)"\_\_proto\_\_: I
```

Permissions bug moved to defect Card #4759

Related Stories
---------------

Card #4293

Tasks
-----

{{ table query: SELECT Number, Name, Owner, 'Task Status' WHERE Type = Task and Story = THIS CARD ORDER BY Status }}

Defects
-------

{{ table query: SELECT Number, Name, Owner, 'Status' WHERE Type = Defect and 'Related Story' = THIS CARD }}

Test Plan
---------

*   QA Test Case: Statuses - Initial Status Mobile (4742)
*   QA: This is currently triggering a Raygun error, ‘script error in’.
*   Test this against objects that do not have status workflow – like FX Forms.

**Comment by githubbob42** [comment]
Tom Jones : 01/18/2017 12:03 CST
It is failing selenium tests

**Comment by githubbob42** [comment]
Matthew Todd : 02/22/2017 14:21 CST
Test Result: Passed PR Build: 4.0.1.pr2242 on 9.0.0 Admin User: qaadmin@test4.com Field User: qafield@test4.com Hardware: Surface Pro 3 OS: Windows 10 Pro Browser: Chrome 56.0.2924.87 (64-bit) URL: https://hunterpeak.herokuapp.com Test Case: Statuses - Initial Status Mobile (4742) Test Notes: Any statuses that don't have a checked 'Initial Status Mobile' no longer appear in the Record Types list when creating a new object.

**Comment by githubbob42** [comment]
**Pull Request #2242**
