### ISSUE TITLE
Add + ticket button not checking ticket create permission

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#4421]
**[Mingle Card: 4759](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/4759)**
Steps to Reproduce
------------------

```
| | |
|-|-|
|**Version #**| |
|**Hardware**| |
|**OS**| |
|**Browser**| |
|**Username**| |
|**Password**|Use LastPass|
|ORG ID| |
|User ID| |
|RayGun Error ID| |
  
 

```

1.  Remove create permission on Ticket
2.  Sync
3.  Navigate to any job’s tickets page

Expected Result
---------------

_Add ticket button does not appear on screen_

Actual Result
-------------

_Add ticket button continues to appear on screen_

_Analysis_
----------

Why can’t we also detect that the user does not have create permission?

For an experiment, I removed access to create a ticket. When I tried to create the ticket in Mobile I got this error:

```
Uncaught (in promise) einner: DOMException: Failed to execute 'put' on 'IDBObjectStore': Evaluating the object store's key path did not yield a value.
    at eval (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:247:29737)
    at eval (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:247:24407)
    at eval (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:247:31934)
    at L (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:247:7845)
    at new B (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:247:6142)
    at eval (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:247:31417)
    at Function.B.newPSD (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:248:18484)
    at G.\_promise (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:247:31276)
    at U.i \[as \_tpf\] (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:247:13269)
    at U.\_idbstore (eval at startWithResources ([https://hunterpeak.herokuapp.com/app/resources.js:1:71](https://hunterpeak.herokuapp.com/app/resources.js:1:71)), <anonymous>:247:24372)message: "Failed to execute 'put' on 'IDBObjectStore': Evaluating the object store's key path did 
```

Related Cards
-------------

Test Plan
---------

This passes the entire suite except for the Filter Performance test

[http://eaglepeak.basecamp.liquidframeworks.com:8080/job/Filter%20Performance%20-%20BR/180/](http://eaglepeak.basecamp.liquidframeworks.com:8080/job/Filter%20Performance%20-%20BR/180/)

**Comment by githubbob42** [comment]
Matthew Todd : 02/20/2017 10:08 CST
Test Result: Passed PR Build: 4.0.1.pr2212 on 9.0.0 Admin User: qaadmin@test4.com Field User: qafield@test4.com Hardware: Surface Pro 3 OS: Windows 10 Pro Browser: Chrome 56.0.2924.87 (64-bit) URL: https://hunterpeak.herokuapp.com Test Case: Create Ticket - No Permissions (4759) Test Notes: With the 'Create' permission unchecked for the 'QA Field' user on the 'Tickets' object and then logging in to Mobile, the blue '+' button is no longer visible on a Job's Ticket page.

**Comment by githubbob42** [comment]
**Pull Request #2212**
