### ISSUE TITLE
Clicking quickly off Reports tab causes "Cannot read property '1' of null" error

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#4571]
**[Mingle Card: 4912](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/4912)**
Steps to Reproduce
------------------

```
| | |
|-|-|
|**Version #**| |
|**Hardware**| |
|**OS**| |
|**Browser**| |
|**Username**| |
|**Password**|Use LastPass|
|ORG ID| |
|User ID| |
|RayGun Error ID| |
  
 

```

Ok, this is wonky to reproduce (unless already on a slow device/machine) and it’s even harder to reproduce now that we’ve added the code to put up the mask until the ticket page(s) are done loading...

1.  login to mobile
2.  open devTools
    1.  goto Timeline tab
    2.  Change, “No CPU Throttling” to “Low end device (5x slowdown)”
3.  goto a Ticket
4.  quickly click between the reports tab and other tabs

Expected Result
---------------

_no errors_

Actual Result
-------------

Uncaught (in promise) TypeError: Cannot read property '1' of null  
    at http://localhost:3000/app/report/list.js:58:31  
    at Array.forEach (native)  
    at getRouteInfo (http://localhost:3000/app/report/list.js:57:10)  
    at ReportList.activate (http://localhost:3000/app/report/list.js:14:21)  
    at tryActivate (http://localhost:3000/vendor/durandal/composition.js:86:40)  
    at Object.bindAndShow (http://localhost:3000/vendor/durandal/composition.js:427:13)  
    at http://localhost:3000/vendor/durandal/composition.js:532:29  
 

_Analysis_
----------

During the activate() function of /reports/list.js, it tries to parse the route info, but since we quickly changed the route, the pattern it’s searching for doesn’t match and it doesn’t account for this and tries to access the matched values.

Related Cards
-------------

Test Plan
---------

**Comment by githubbob42** [comment]
**Pull Request #2280**

**Comment by githubbob42** [comment]
Matthew Todd : 03/21/2017 10:17 CDT
Test Result: Passed PR Build: 4.0.1.pr2280 on 9.1.3 Admin User: qaadmin@test4.com Field User: qafield@test4.com Hardware: Surface Pro 3 OS: Windows 10 Pro Browser: Chrome 57.0.2987.110 (64-bit) URL: https://hunterpeak.herokuapp.com Test Case: #4912 Reproduction Steps and Mobile Regression Test Notes: You can now successfully navigate to and from Reports quickly and it won't cause any issues. Tested on the different tabs under Jobs and no issues was seen on this PR, but I had a faliure on master.
