### ISSUE TITLE
Add ability to refresh OAuth token in alpine-post for AuditLog processing

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#4584]
**[Mingle Card: 4925](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/4925)**
Steps to Reproduce
------------------

```
| | |
|-|-|
|**Version #**| |
|**Hardware**| |
|**OS**| |
|**Browser**| |
|**Username**| |
|**Password**|Use LastPass|
|ORG ID| |
|User ID| |
|RayGun Error ID| |
  
 

```

Not sure how to test this but I’m sure that illustrious quality assurance engineers can figure a way :-) 

1.  Expire your token (???)
2.  Click Sync

Expected Result
---------------

_It should try to refresh your oauth token (if expired) and then try to create the AuditLog entry_

Actual Result
-------------

» 6 Mar 2017 14:41:47.976 144 <190>1 2017-03-06T20:41:47.680854+00:00 app web.9 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ authenticate Heroku/fieldfx Context

» 6 Mar 2017 14:42:20.625 145 <190>1 2017-03-06T20:42:20.297342+00:00 app web.17 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ authenticate Heroku/fieldfx Context

» 6 Mar 2017 14:42:20.709 145 <190>1 2017-03-06T20:42:20.414009+00:00 app web.20 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ authenticate Heroku/fieldfx Context

» 6 Mar 2017 14:42:20.900 180 <190>1 2017-03-06T20:42:20.609797+00:00 app web.11 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Domain originating the request: www.fieldfx.com Heroku/fieldfx Context

» 6 Mar 2017 14:42:20.960 180 <190>1 2017-03-06T20:42:20.656717+00:00 app web.12 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Domain originating the request: www.fieldfx.com Heroku/fieldfx Context

» 6 Mar 2017 14:42:28.806 205 <190>1 2017-03-06T20:42:28.510164+00:00 app web.9 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Failed to create mixpanel:Logout event: Error: Session expired or invalid Heroku/fieldfx Context

» 6 Mar 2017 14:42:28.915 207.140.199.218 pxndwsi3 LOG '00D1a000000KXoUEAW/0051a000000zlnEAAQ Logging out with unsynced data' Heroku/javascript log Context

» 6 Mar 2017 14:42:29.334 168 <190>1 2017-03-06T20:42:29.045897+00:00 app web.9 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Audit Log Insert Failed: retrying: 1 Heroku/fieldfx Context

» 6 Mar 2017 14:42:29.866 168 <190>1 2017-03-06T20:42:29.580897+00:00 app web.9 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Audit Log Insert Failed: retrying: 2 Heroku/fieldfx Context

» 6 Mar 2017 14:42:29.937 189 <190>1 2017-03-06T20:42:29.626563+00:00 app web.9 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Audit Log Insert Failed: continue processing sync package Heroku/fieldfx Context

» 6 Mar 2017 14:42:29.937 193 <190>1 2017-03-06T20:42:29.626651+00:00 app web.9 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Audit Log Attachment Failed: continue processing sync package AuditLog Heroku/fieldfx Context

» 6 Mar 2017 14:42:30.088 194 <190>1 2017-03-06T20:42:29.786703+00:00 app worker.1 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Logging: Processing queue item: id=58bdc9b5823c1c0400a85fb4 Heroku/fieldfx Context

» 6 Mar 2017 14:42:30.088 686 <190>1 2017-03-06T20:42:29.860813+00:00 app worker.1 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Logging: Failed to log the following server exception: {"id":"58bdc9b5823c1c0400a85fb4","error":"Error: Session expired or invalid\\n at /app/node\_modules/nforce/index.js:1170:15\\n at IncomingMessage.<anonymous> (/app/node\_modules/nforce/index.js:1034:9)\\n at emitNone (events.js:91:20)\\n at IncomingMessage.emit (events.js:185:7)\\n at endReadableNT (\_stream\_readable.js:974:12)\\n at \_combinedTickCallback (internal/process/next\_tick.js:74:11)\\n at process.\_tickCallback (internal/process/next\_tick.js:98:9)","ElapsedTime":"74 ms"} Heroku/fieldfx Context

» 6 Mar 2017 14:42:30.088 223 <190>1 2017-03-06T20:42:29.864862+00:00 app worker.1 - - 00D1a000000KXoUEAW/0051a000000zlnEAAQ Logging: Processing queue item complete: id=58bdc9b5823c1c0400a85fb4 Elapsed Time: 74 ms Heroku/fieldfx Context

_Analysis_
----------

The aouth token has apparently expired and we are not checking it and refreshing it.  Add ability to refresh an expired token.

Normally this shouldn’t happen, but looking at the logs, it appears that the use logged out (with unsynced data) but his token must have been expired.  And we don’t force a login on a logout which would have refreshed/recreated the token. 

The only other scenario in which post may try to process a packet with an expired token would be if alpine-post had crashed for an extended period of time.

Related Cards
-------------

Test Plan
---------

Good luck testing this one!

BR: I don’t remember how I tested this.  I thought I added notes here.  I’m pretty sure I set the session timeout to the minimum in the backoffice.  I may or may not have revoked the users session and/or I just waited a little longer than the session timeout.

**Comment by githubbob42** [comment]
**Pull Request #46**
