### ISSUE TITLE
Post failed for unknown reason

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#4693]
**[Mingle Card: 5040](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/5040)**
Steps to Reproduce
------------------

```
| | |
|-|-|
|**Version #**| |
|**Hardware**| |
|**OS**| |
|**Browser**| |
|**Username**| |
|**Password**|Use LastPass|
|ORG ID| |
|User ID| |
|RayGun Error ID| |
  


```

```
| | |
|-|-|

  
   
   

**Audit Log ID**

   |
   
   

AL-660

   |
   
   

**Owner**

   |
   
   

[Scott Brunson](https://veolia.my.salesforce.com/00538000004tTOn) [\[Change\]](https://veolia.my.salesforce.com/a053800000jNW2C/a?retURL=%2Fa053800000jNW2C)

   |
  
   
   

**Type**

   |
   
   

SyncUploadError

   |
   
   

**Package Id**

   |
   
   

58f9095fc214fc0400e78e4e

   |
  
   
   

**User**

   |
   
   

[Scott Brunson](https://veolia.my.salesforce.com/00538000004tTOn)

   |
   
   

**Event Id**

   |
   
   

   |
  
   
   

**Notes**

   |
   
   

   |
   
   

**Tracking Number**

   |
   
   

   |
  
   
   

**Event Date**

   |
   
   

4/20/2017 2:20 PM

   |
   
   

**URL**

   |
   
   

[https://www.fieldfx.com/syncerrors/58f9095fc214...](https://www.fieldfx.com/syncerrors/58f9095fc214fc0400e78e4e)

   |
  
   
   

**Resolved**

   |
   
   

   |
   
   

**IP Address**

   |
   
   

   |
  
   
   

   |
   
   

   |
   
   

**Message**

   |
   
   

Unknown salesforce upload error

   |
  
   
   

**Created By**

   |
   
   

[Scott Brunson](https://veolia.my.salesforce.com/00538000004tTOn), 4/20/2017 2:20 PM

   |
   
   

**Last Modified By**

   |
   
   

[Scott Brunson](https://veolia.my.salesforce.com/00538000004tTOn), 4/20/2017 2:20 PM

   |
  
   
   

**Agreed To License**

   |
   
   

No

   |
   
   

   |
   
   

   |
  


```

```
145 <190>1 2017-04-20T19:20:21.927744+00:00 host app post.1 - 00D500000007gXKEAY/00538000004tTOnAAM Model: processing event-queued id: 1492707938124
105 <190>1 2017-04-20T19:20:22.144248+00:00 host app post.1 - source=00D500000007gXKEAY count#upload.error=1
183 <190>1 2017-04-20T19:20:22.144833+00:00 host app post.1 - 00D500000007gXKEAY/00538000004tTOnAAM Post: Failed to send the following sync message to sforce: id=58f9095fc214fc0400e78e4e
186 <190>1 2017-04-20T19:20:22.189918+00:00 host app post.1 - 00D500000007gXKEAY/00538000004tTOnAAM Post: Processing queue item complete: id=58f9095fc214fc0400e78e4e Elapsed Time: 150149 ms
158 <190>1 2017-04-20T19:20:22.254147+00:00 host app worker.1 - 00D500000007gXKEAY/00538000004tTOnAAM Logging: Processing queue item: id=58f909f6c15a5a0400449bcb
80 <190>1 2017-04-20T19:20:22.913966+00:00 host app worker.1 - util is not defined
96 <190>1 2017-04-20T19:20:22.913967+00:00 host app worker.1 - ReferenceError: util is not defined
143 <190>1 2017-04-20T19:20:22.913968+00:00 host app worker.1 -     at authenticateFailed (/app/node\_modules/alpine-post/lib/connection.js:101:28)
111 <190>1 2017-04-20T19:20:22.913969+00:00 host app worker.1 -     at \_rejected (/app/node\_modules/q/q.js:864:24)
99 <190>1 2017-04-20T19:20:22.913970+00:00 host app worker.1 -     at /app/node\_modules/q/q.js:890:30
115 <190>1 2017-04-20T19:20:22.913970+00:00 host app worker.1 -     at Promise.when (/app/node\_modules/q/q.js:1142:31)
133 <190>1 2017-04-20T19:20:22.913971+00:00 host app worker.1 -     at Promise.promise.promiseDispatch (/app/node\_modules/q/q.js:808:41)
99 <190>1 2017-04-20T19:20:22.913972+00:00 host app worker.1 -     at /app/node\_modules/q/q.js:624:44
111 <190>1 2017-04-20T19:20:22.913973+00:00 host app worker.1 -     at runSingle (/app/node\_modules/q/q.js:137:13)
107 <190>1 2017-04-20T19:20:22.913973+00:00 host app worker.1 -     at flush (/app/node\_modules/q/q.js:125:13)
126 <190>1 2017-04-20T19:20:22.913974+00:00 host app worker.1 -     at \_combinedTickCallback (internal/process/next\_tick.js:67:7)
126 <190>1 2017-04-20T19:20:22.913975+00:00 host app worker.1 -     at process.\_tickCallback (internal/process/next\_tick.js:98:9)
188 <190>1 2017-04-20T19:20:22.915585+00:00 host app worker.1 - 00D500000007gXKEAY/00538000004tTOnAAM Logging: Processing queue item complete: id=58f909f6c15a5a0400449bcb Elapsed Time: 660 ms
169 <190>1 2017-04-20T19:20:22.913953+00:00 host app worker.1 - SERVERERROR -orgName: Veolia North America -userName: scott.brunson@veolia.com -errorDetails: ReferenceError


```

Expected Result
---------------

_What should happen?_

Actual Result
-------------

_What actually happens?_

_Analysis_
----------

need to require util module.

missing linting

Related Cards
-------------

Test Plan
---------

**Comment by githubbob42** [comment]
**Pull Request #48**
