### ISSUE TITLE
TECH DEBT: use hostname instead of host

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#5280]
**[Mingle Card: 5638](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/5638)**
Trolling through the server logs, I came across this log repeated numerous times (725 times in the last month):

express deprecated req.host: Use req.hostname instead at redirect-https.js:5:48

Server repo/branch: githubbob42 / card5638\_host2hostname

[https://github.com/Liquidframeworks/alpine-server/pull/253](https://github.com/Liquidframeworks/alpine-server/pull/253)

### Test Plan

Run a full selenium suite

1.  Deploy Server repo/branch: githubbob42 / card5638\_host2hostname2.
2.  Verify the messages are gone in LogEntries

Test Result: Pass
-----------------

PR: 253

User: [lanrefield@seven.com](mailto:lanrefield@seven.com) / lastpass      
Hardware: Dell PC & IPAD  
OS:  Windows 10 & IOS 11  
Browser: Chrome & Safari

[https://fxqa6.herokuapp.com/](https://fxqa6.herokuapp.com/)

**Test case:   ** We wont worry about adding this to the regression tests.  Bob was only getting rid of a warnings from the logs.

**Test Notes: ** After deploying the changes to fxqa6 i was able to verify that the phrase “express deprecated req.host: Use req.hostname instead at redirect-https.js:5:48" is not included anywhere in the log entries.

1st Full Sync was at 8.26am

2nd Full Sync was at 9.17am

1st Incremental Sync was at 9.38am

2nd Incremental Sync was at 9.50am

!Capture-6f246e.JPG!

**Comment by githubbob42** [comment]
**Pull Request #253**
