### ISSUE TITLE
CDN: sometimes salesforce errors are passed into error handler

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#5661]
**[Mingle Card: 6024](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/6024)**
Steps to Reproduce
------------------

```
| | |
|-|-|
|**Version #**| |
|**Hardware**| |
|**OS**| |
|**Browser**| |
|**Username**| |
|**Password**|Use LastPass|
|ORG ID| |
|User ID| |
|RayGun Error ID| |
  
 

```

1.  Do this
2.  Then do that
3.  Followed by this

Expected Result
---------------

_We should handle different types of error results_

Actual Result
-------------

_From LogEntries:_

2018-10-03T14:29:19.873024+00:00 host app web.1 \- undefined -orgId: 00D0S0000008z1qUAA -userId: 0050S000001N1duQAC -errorDetails: undefined

_Analysis_
----------

Currently the error handler middleware in cdn is only expecting a JavaScript error.  We occasionally get what appear to be salesforce errors:

2018-10-03T14:29:19.873024+00:00 host app web.1 \- undefined -orgId: 00D0S0000008z1qUAA -userId: 0050S000001N1duQAC -errorDetails: undefined

I added some code while testing locally and logged the following from the error handler:

```
err: { error: '\[{"message":"Session expired or invalid","errorCode":"INVALID\_SESSION\_ID"}\]',
 options: 
 { url: 'https://besdevorg-bes.cs52.force.com/services/apexrest/FX5/ping?namespace=FX5',
 headers: 
 { 'Content-Type': 'text/xml;charset=UTF-8',
 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10\_8\_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1521.3 Safari/537.36' },
 auth: { bearer: '00Di0000000el2B!AQUAQGKEWx2G5e\_8khUAQzLYP5UziTObhNWHMvNqD5SLTccy8vFE2er8Ib3mYDElXKDFnC6A6zJMpSj\_A\_GvVopqcEJ\_V4EL' },
 method: 'GET',
```

* * *

So it looks like we have a couple of problems.  Whenever we call into the errorhandler, we subsequently call into the Express.js default error handler, which:

[https://expressjs.com/en/guide/error-handling.html](https://expressjs.com/en/guide/error-handling.html)

> If you pass an error to `next()` and you do not handle it in a custom error handler, it will be handled by the built-in error handler; the error will be written to the client with the stack trace

This appears to mean that if you don’t “handle it”, as in setStatus() and send(), then you should send to the default error handler, which apparently, based on the error, writes the status and message to the client.  But we chained a then() off of the catch() and if no result (i.e. error occurred) we try to setStatus() and send (again), thus throwing the error: 

```
Possibly unhandled Error: Can't set headers after they are sent.
 at ServerResponse.OutgoingMessage.setHeader (\_http\_outgoing.js:356:11)
 at ServerResponse.header (/Users/broth/projects/cdn/node\_modules/express/lib/response.js:718:10)
 at ServerResponse.send (/Users/broth/projects/cdn/node\_modules/express/lib/response.js:163:12)
 at /Users/broth/projects/cdn/verify-session.js:110:27
 at tryCatcher (/Users/broth/projects/cdn/node\_modules/bluebird/js/main/util.js:26:23)
 at Promise.\_settlePromiseFromHandler (/Users/broth/projects/cdn/node\_modules/bluebird/js/main/promise.js:510:31)
 at Promise.\_settlePromiseAt (/Users/broth/projects/cdn/node\_modules/bluebird/js/main/promise.js:584:18)
 at Promise.\_settlePromises (/Users/broth/projects/cdn/node\_modules/bluebird/js/main/promise.js:700:14)
 at Async.\_drainQueue (/Users/broth/projects/cdn/node\_modules/bluebird/js/main/async.js:123:16)
 at Async.\_drainQueues (/Users/broth/projects/cdn/node\_modules/bluebird/js/main/async.js:133:10)
 at Immediate.Async.drainQueues (/Users/broth/projects/cdn/node\_modules/bluebird/js/main/async.js:15:14)
 at runCallback (timers.js:672:20)
 at tryOnImmediate (timers.js:645:5)
 at processImmediate \[as \_immediateCallback\] (timers.js:617:5)
```

So, we can either not call next(err) from within our errorHandler() method, or we can move the 

Related Cards
-------------

Impact Analysis
---------------

_Developers: Fill in this area during code review._

​

Test Plan
---------

Hmmm, open TIB and Dev Tools and either:

*   view the source and get the url to cdn from the <script> tag or
*   (easier) open the Network tab and search for mainjs (no period) and copy the url from the information tab

past into a browser… crap that won’t work because it won’t pass the check-referer test.

**Comment by githubbob42** [comment]
**Pull Request #32**
