### ISSUE TITLE
Sync failing with error developername is null

### ISSUE THREAD

**Issue by githubbob42** [githubbob42/mingle2github2#949]
**[Mingle Card: 1119](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/1119)**
DP 2014.02.17- It is possible to remove all assigned record types for ticket from a profile and then give it -Master- as it's default record type.  In mobile this allows a user to create a record with no record type.  In mobile nothing crashes, it simply blocks the user from creating new tickets.  This is considered reasonable behavior according to Tom.

Dev Notes:
----------

A change in the code fixed this issue sometime back. As is indicated on the update section below, the app allowed the user to create 3 tickets without a record type, something that should never have happened..

Steps to reproduce
------------------

**OS: All**

**Browser: All**

**Username/Password: jgirard@demo.com/carrington#2**

1.  Login to fxdemo 
2.  Sync

Expected result
---------------

The error is probably valid but we need to understand where the error came from and get a better error message.

UPDATE:

Justin came by and said that the sales guys used Mobile to create 3 tickets with no record type. He says that he knows the tickets were created in Mobile because the created in Mobile flag was set.

Actual Result
-------------

```
SERVERERROR -orgId: 00Di0000000ejIyEAI -userId: 005i0000001c17aAAA -errorDetails: 

TypeError: Cannot read property 'DeveloperName' of null 

at /app/sync/sync-utils.js:117:37 

at Array.forEach (native) 

at Object.exports.mapNewItem (/app/sync/sync-utils.js:110:12) 

at mapToTicket (/app/sync/steps/tickets.js:99:28) 

at Array.map (native) 

at createTicketDataPackage (/app/sync/steps/tickets.js:115:92) 

at /app/node\_modules/q/q.js:958:30 EXCEPT
```

Related Cards
-------------

**Comment by githubbob42** [comment]
### Related Story: #102 Sync ([Mingle](https://liquidframeworks.mingle.thoughtworks.com/projects/alpine_mobile/cards/214))
